name: Docker Image CI

on:
  push:
    branches: [ "*" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch master branch
        run: git fetch origin master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Docker Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # github username or org
          password: ${{ secrets.GITHUB_TOKEN }}    # github actions builtin token. repo has to have pkg access.
      
      - name: Determine tag name
        id: tag_name
        run: echo ::set-output name=TAG_NAME::$(if [ "${GITHUB_REF##*/}" == "master" ]; then echo "latest"; else echo "deepak7340-${GITHUB_REF##*/}"; fi)

      - name: Find Image Directories
        id: image_dir
        run: |
          IMAGE_DIR=$(git diff origin/master --stat -- * | grep -v "files changed"| cut -d "/" -f 1 | sort -u |tr -d ' ')
          echo "Image directorie: $Image_DIR"
          echo "::set-output name=image_dir::$IMAGE_DIR"

      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      
      - name: Build and push
        env:
          TAG: ${{ steps.tag_name.outputs.TAG_NAME }}
          IMAGE_DIR: ${{ steps.image_dir.outputs.IMAGE_DIR }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ env.IMAGE_DIR }}/Dockerfile
          platforms: linux/amd64
          pull: true # Pull new version of base image, always; avoid bit-rot
          push: true
          labels: |
            org.opencontainers.image.title=${{ github.repository }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
          cache-from: type=gha # all-automatic Github Actions caching
          cache-to: type=gha,mode=max
          build-args: |
            TAG=${TAG}
          tags: ghcr.io/deepak7340/${{ env.IMAGE_DIR }}:${{ env.TAG }}
