name: Build mongodb backup

on:
    push:
#      branches: [ "master" ]
      paths: 'mongodb-backup/**'
#      tags: '*'
    pull_request:
#      branches: [ "master" ]
      paths: 'mongodb-backup/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Branch Name
        id: get_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Build Docker image and tag with branch name
        run: |
          branch="${{ steps.get_branch.outputs.branch }}"
          if [[ "$branch" == "master" ]]; then
            image_tag="latest"
          else
            image_tag="$branch"
          fi
          docker buildx build --tag ghcr.io/mongodb-backup:$image_tag .
      
      - name: Push Docker image
        run: |
          branch="${{ steps.get_branch.outputs.branch }}"
          docker push ghcr.io/mongodb-backup:"$branch"
          if [[ "$branch" == "master" ]]; then
            docker push ghcr.io/mongodb-backup:latest
          fi
