name: Build & publish mongodump images

on:
  workflow_run:
    workflows: 
      - "mongodump"
    types: 
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./mongodb-backup/Dockerfile
            image: ghcr.io/deepak7340/mongodbbackup
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # github username or org
          password: ${{ secrets.GITHUB_TOKEN }}    # github actions builtin token. repo has to have pkg access.

      - name: Extract metadata (tags, labels) for image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Determine Image Tag
        id: image-tag
        run: |
          if [ "${{ steps.meta.outputs.tags }}" = "master" ]; then
            echo "::set-output name=tag::latest"
          else
            echo ${{ steps.meta.outputs.tags }}
          fi

      - name: Build and push image
        env:
          IMAGE_TAG: ${{ steps.image-tag.outputs.tag }}
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ env.IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
