name: Build mongodb backup

on:
    push:
#      branches: [ "master" ]
      paths: 'mongodb-backup/**'
#      tags: '*'
    pull_request:
#      branches: [ "master" ]
      paths: 'mongodb-backup/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate container metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: dockerfiles/mongodb-backup
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=sha,prefix={{branch}}-
            type=sha,format=long
            type=sha,format=long,prefix={{branch}}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push container image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=dockerfiles/mongodb-backup:latest
          cache-to: type=inline
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
